### ISSUE TITLE
problem on running

### ISSUE THREAD

**Issue by martinorob** [FissionCat/Hue-Disco#3]
Hi! 
may you help me on installing HueDisco?

thanks
Martino

**Comment by aycgit** [comment]
https://github.com/FissionCat/Hue-Disco/blob/master/README.md

**Comment by aycgit** [comment]
#1yearoldissue

**Comment by FissionCat** [comment]
@martinorob I'm closing this for now, since as @aycgit points out, it is an old issue, but if you're still having problems and can point me to something more specific that's going wrong (e.g. an error message you're getting), do open another issue.
